Categories:
  - Development
License: MIT
AuthorName: secext2022
AuthorEmail: secext2022@outlook.com
SourceCode: https://github.com/fm-elpac/azi
IssueTracker: https://github.com/fm-elpac/azi/issues
RepoType: git
Repo: https://github.com/fm-elpac/azi
Builds:
  - versionName: 0.1.0
    versionCode: 2
    commit: HEAD
    sudo:
      - apt-get update
      - apt-get install -y build-essential npm zip
    output: demo-apk/app/build/outputs/apk/release/app-release-unsigned.apk
    srclibs:
      - rustup@1.28.2
    prebuild:
      - $$rustup$$/rustup-init.sh -y --target aarch64-linux-android
    build:
      - source $HOME/.cargo/env
      - make BUILD=fdroid all
    ndk: r28b
#AutoUpdateMode: Version
#UpdateCheckMode: Tags v[0-9].*
#UpdateCheckData: demo-apk/app/build.gradle.kts|versionCode\s=\s(\d+)|.|versionName\s=\s"([^"]+)"
