name: CI

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - uses: denoland/setup-deno@v2
        with:
          deno-version: v2.x

      - uses: actions/setup-java@v4
        with:
          distribution: "temurin"
          java-version: "17"

      - run: deno fmt --check

      # azi-unzip
      - run: rustup target add aarch64-linux-android
      - run: cd azi-unzip && cargo fmt --check
      - run: cd azi-unzip && cargo build
      - run: cd azi-unzip && cargo test
      # aarch64-linux-android
      - run: |
          export PATH=$ANDROID_NDK_HOME/toolchains/llvm/prebuilt/linux-x86_64/bin:$PATH && \
          cargo build --target aarch64-linux-android --release
        env:
          CARGO_TARGET_AARCH64_LINUX_ANDROID_LINKER: aarch64-linux-android28-clang
          AR_aarch64_linux_android: llvm-ar
          CC_aarch64_linux_android: aarch64-linux-android28-clang
      # upload
      - run: cp azi-unzip/target/aarch64-linux-android/release/azi-unzip unzip
      - uses: actions/upload-artifact@v4
        with:
          name: azi-unzip
          path: unzip

      - run: mkdir -p azi-aar/libazi/src/main/assets/azi && cp unzip azi-aar/libazi/src/main/assets/azi/
      # TODO

      # azi.aar
      - run: cd azi-aar && ./gradlew assemble
      # upload
      - run: cp azi-aar/libazi/build/outputs/aar/libazi-release.aar azi.aar
      - uses: actions/upload-artifact@v4
        with:
          name: azi-aar
          path: azi.aar

      # cp azi.aar
      - run: mkdir -p demo-apk/app/libs && cp azi.aar demo-apk/app/libs/

      # azi-demo.apk
      - run: cd demo-apk && ./gradlew assemble
      # upload
      - run: cp demo-apk/app/build/outputs/apk/debug/app-debug.apk azi-demo-debug.apk
      - uses: actions/upload-artifact@v4
        with:
          name: azi-demo-debug.apk
          path: azi-demo-debug.apk

      # TODO
