name: CI

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - uses: denoland/setup-deno@v2
        with:
          deno-version: v2.x
      - uses: actions/setup-java@v4
        with:
          distribution: "temurin"
          java-version: "17"

      - run: deno fmt --check

      # azi-unzip
      - run: rustup target add aarch64-linux-android
      - run: cd azi-unzip && cargo fmt --check
      - run: cd azi-unzip && cargo build
      - run: cd azi-unzip && cargo test
      # aarch64-linux-android
      - run: make azi-unzip
      # upload
      - run: cp azi-unzip/target/aarch64-linux-android/release/azi-unzip unzip
      - uses: actions/upload-artifact@v4
        with:
          name: azi-unzip
          path: unzip

      # azi-loader.zip
      - run: make npm-setup ui-loader
      # upload
      - uses: actions/upload-artifact@v4
        with:
          name: azi-loader
          path: azi-aar/libazi/src/main/assets/azi/loader

      # azi.aar
      - run: make azi-aar
      # upload
      - run: cp azi-aar/libazi/build/outputs/aar/libazi-release.aar azi.aar
      - uses: actions/upload-artifact@v4
        with:
          name: azi-aar
          path: azi.aar

      # azi-demo.apk
      - run: make demo-apk
      # upload
      - run: cp demo-apk/app/build/outputs/apk/debug/app-debug.apk azi-demo-debug.apk
      - uses: actions/upload-artifact@v4
        with:
          name: azi-demo-debug.apk
          path: azi-demo-debug.apk

      # TODO
